Name: Bhumi Naik

Roll No: 23102A0070

R-Programming Lab 9

## 1. `print()` limitation

The NPTEL notes show that `print()` prints one object at a time. Trying to pass multiple items directly produces an error.

In [2]:
# Printing the items one at a time
print("The zero occurs at")
print(2*pi)
print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

## 2. `cat()` function

`cat()` concatenates its arguments and prints them as continuous output. By default, it separates items with a space. A newline can be supplied using `\n`.

In [3]:
cat("The zero occurs at", 2*pi, "radians.", "\n")

The zero occurs at 6.283185 radians.

In [4]:
# Date example from the notes
d = date()
cat("Today's date is:", d, "\n")

Today's date is: Tue Oct  6 15:47:00 2026

In [5]:
# Using sep with a vector
x = 1:10
x

cat(x, sep = " ++ ")
cat("\n")
cat(x, sep = " / ")
cat("\n")

 [1]  1  2  3  4  5  6  7  8  9 10

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10
1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

In [6]:
# Printing a calculated value
x = 7
cat("The square of", x, "is", x^2, "!\n")

The square of 7 is 49 !

In [7]:
# Using format() inside cat()
cat(
  "The square root of", x,
  "is approximately",
  format(sqrt(x), digits = 3),
  "\n"
)

The square root of 7 is approximately 2.65

In [8]:
# cat() with a simple vector
evenno = c(2, 4, 6, 8, 10)

cat("The first few even numbers are:", evenno, "...\n")

The first few even numbers are: 2 4 6 8 10 ...

In [9]:
# cat() with fill and labels
x = 1:10

cat(
  x,
  fill = 2,
  labels = paste("(", letters[1:10], "):")
)

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

## 3. `paste()` function

`paste()` concatenates strings and returns the result, so the result can be assigned to a variable.  
`sep` controls the separator between input arguments, while `collapse` combines the resulting elements into one string.

In [10]:
# Basic paste()
paste("Everybody", "loves", "R Programming.")

[1] "Everybody loves R Programming."

In [11]:
# Different separators
paste("Everybody", "loves", "R Programming.", sep = "*")

paste("Everybody", "loves", "R Programming.", sep = "===")

[1] "Everybody*loves*R Programming."

[1] "Everybody===loves===R Programming."

In [12]:
# paste() converts its arguments to character strings
paste(1:12)

# Alternative shown in the notes
as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [13]:
# Vector of names
names = c("Prof. Singh", "Mr. Venkat", "Dr. Jha")

names

paste(names, "is", "a good", "person.")

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

[1] "Prof. Singh is a good person." "Mr. Venkat is a good person."
[3] "Dr. Jha is a good person."

In [14]:
# Using collapse to join the generated strings
paste(
  names,
  "is",
  "a good",
  "person.",
  collapse = ", and "
)

[1] "Prof. Singh is a good person., and Mr. Venkat is a good person., and Dr. Jha is a good person."

## 4. Operations with strings using `paste()`

The notes demonstrate how spaces inside quoted strings are preserved and how `sep` affects the output.

In [15]:
paste(
  1, " is first",
  2, " is second",
  3, " is third",
  sep = "#"
)

[1] "1# is first#2# is second#3# is third"

In [16]:
# Notice the spaces inside the quoted strings
paste(
  1, " is first ",
  2, " is second ",
  3, " is third ",
  sep = "#"
)

[1] "1# is first #2# is second #3# is third "

In [17]:
# Creating a vector of strings
x = paste("Ex", 1:5, sep = "_")

x

x[1]
x[2]
x[3]
x[5]

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

[1] "Ex_1"

[1] "Ex_2"

[1] "Ex_3"

[1] "Ex_5"

In [18]:
# Using collapse creates one single string
x = paste("Ex", 1:5, sep = "_", collapse = "")

x
x[1]

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

### Difference between `sep` and `collapse`

Without `collapse`, `paste()` produces a vector of strings. With `collapse`, those resulting strings are joined into one string.

In [19]:
# Vector result
x = paste("Ex", 1:5, sep = "_")
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [20]:
# Single collapsed string
x = paste("Ex", 1:5, sep = "_", collapse = "")
x

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [21]:
# paste0() and paste() with a single vector
paste0(1:10)
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [22]:
# Vectorized paste0()
paste0(
  1:10,
  c("st", "nd", "rd", rep("th", 7))
)

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

In [23]:
# paste() inserts a space by default
paste(
  1:10,
  c("st", "nd", "rd", rep("th", 7))
)

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

## 5. `strsplit()` – String Splitting

`strsplit()` splits each element of a character vector using the supplied `split` pattern. The result is a list.

In [24]:
# Example from the NPTEL notes
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

x

strsplit(x, split = "!")

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The&"                "syntax&"             "of&"
[4] "paste&"              "is"                  "&available"
[7] " &inthe online-help"

In [25]:
# Splitting using "&!"
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

x

strsplit(x, split = "&!")

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The"                               "syntax"
[3] "of"                                "paste"
[5] "is!&available! &inthe online-help"

In [26]:
# Splitting using "!&"
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

x

y = strsplit(x, split = "!&")

y

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The&!syntax&!of&!paste&!is"    "available! &inthe online-help"

In [27]:
# Accessing individual components of the list returned by strsplit()
y[[1]][1]
y[[1]][2]
y[[1]][3]

[1] "The&!syntax&!of&!paste&!is"

[1] "available! &inthe online-help"

[1] NA

## 6. `strsplit()` – Convert dates into a matrix

The notes demonstrate splitting date strings using `-`, then converting the resulting list into a matrix.

In [28]:
dates = c(
  "2020-07-24",
  "2021-08-25",
  "2022-09-26",
  "2023-10-27"
)

dates

[1] "2020-07-24" "2021-08-25" "2022-09-26" "2023-10-27"

In [29]:
# Split each date into year, month and day
datesplt = strsplit(dates, "-")

datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

In [30]:
# Matrix with character values
datemat = matrix(
  unlist(datesplt),
  nrow = 4,
  ncol = 3,
  byrow = TRUE
)

datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

In [31]:
# Matrix with numeric values
datematrix = matrix(
  as.numeric(unlist(datesplt)),
  nrow = 4,
  ncol = 3,
  byrow = TRUE
)

datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

In [32]:
# Splitting a word into individual characters
strsplit("Shalabh", split = "")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

## 7. Counting characters with `nchar()`

`nchar()` returns the number of characters in each element of its input. `nzchar()` checks whether elements are non-empty strings.

In [33]:
x = "R course 24.07.2022"
y = "Number of participants: 25"

nchar(x)
nchar(y)

[1] 19

[1] 26

In [34]:
# nzchar() returns TRUE for non-empty strings
x = "R course 24.07.2022"
y = "Number of participants: 25"

nzchar(x)
nzchar(y)

[1] TRUE

[1] TRUE

In [35]:
# nzchar() with a character vector
x = c("Apple", "Banana", "Cake")

x
nzchar(x)

[1] "Apple"  "Banana" "Cake"

[1] TRUE TRUE TRUE

In [36]:
# Empty string example
y = c("Apple", "", "Cake")

y
nzchar(y)

[1] "Apple" ""      "Cake"

[1]  TRUE FALSE  TRUE

In [37]:
# nchar() with character vectors
x = c("Apple", "Banana", "Cake")

nchar(x)

[1] 5 6 4

In [38]:
# nchar() can also operate on numeric values
y = c(2, 4, 6)
nchar(y)

z = c(11, 222, 3333)
nchar(z)

z1 = c(1.1, 2.22, 3.333)
nchar(z1)

[1] 1 1 1

[1] 2 3 4

[1] 3 4 5

## 8. Changing lower and upper case

`tolower()` converts uppercase letters to lowercase, while `toupper()` converts lowercase letters to uppercase. Non-alphabetic characters remain unchanged.

In [39]:
x = "R course will start from 24.07.2022"

toupper(x)

[1] "R COURSE WILL START FROM 24.07.2022"

In [40]:
z = "INDIAN INSTITUTE OF TECHNOLOGY"

tolower(z)

[1] "indian institute of technology"

## 9. Combined practice examples

These examples combine the string functions covered in Lectures 36–39 and can be executed directly.

In [41]:
# Example 1: Build and print a message
student = "Aarti"
course = "R Programming"
week = 9

message = paste(
  "Student:", student,
  "| Course:", course,
  "| Week:", week
)

cat(message, "\n")

Student: Aarti | Course: R Programming | Week: 9

In [42]:
# Example 2: Create formatted exercise names
exercises = paste("Exercise", 1:5, sep = "_")

exercises

[1] "Exercise_1" "Exercise_2" "Exercise_3" "Exercise_4" "Exercise_5"

In [43]:
# Example 3: Join exercise names into one string
paste(exercises, collapse = ", ")

[1] "Exercise_1, Exercise_2, Exercise_3, Exercise_4, Exercise_5"

In [44]:
# Example 4: Split a date and display its components
date_value = "2026-10-06"

parts = strsplit(date_value, "-")[[1]]

cat(
  "Year:", parts[1],
  "| Month:", parts[2],
  "| Day:", parts[3],
  "\n"
)

Year: 2026 | Month: 10 | Day: 06

In [45]:
# Example 5: Character count and case conversion
text_value = "R Programming Week 9"

cat("Text:", text_value, "\n")
cat("Number of characters:", nchar(text_value), "\n")
cat("Uppercase:", toupper(text_value), "\n")
cat("Lowercase:", tolower(text_value), "\n")

Text: R Programming Week 9
Number of characters: 20
Uppercase: R PROGRAMMING WEEK 9
Lowercase: r programming week 9